name: Publish NuGet Package

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output
  NUGET_SOURCE_URL: 'https://nuget.pkg.github.com/pure-delivery-org/index.json'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore SharedContracts/SharedContracts/PureDelivery.Shared.Contracts.csproj
      
    - name: Build
      run: dotnet build SharedContracts/SharedContracts/PureDelivery.Shared.Contracts.csproj --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal

  publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore SharedContracts/SharedContracts/PureDelivery.Shared.Contracts.csproj
      
    - name: Build
      run: dotnet build SharedContracts/SharedContracts/PureDelivery.Shared.Contracts.csproj --configuration Release --no-restore
      
    - name: Create NuGet package
      run: dotnet pack SharedContracts/SharedContracts/PureDelivery.Shared.Contracts.csproj --configuration Release --no-build --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}
      
    - name: Publish to GitHub Packages
      run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg --source ${{ env.NUGET_SOURCE_URL }} --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate